Pretty printed with shfmt. See Makefile

diff --git a/git-proj-clone b/git-proj-clone
--- a/git-proj-clone
+++ b/git-proj-clone
@@ -3,9 +3,9 @@
 #--------------------
 fUsage()
 {
-	exit 1
-	
-	cat <<EOF >/dev/null
+    exit 1
+
+    cat <<EOF >/dev/null
 git proj clone pExternalPath
 
     Clone a local git repo from the external pDirPath.
@@ -24,44 +24,44 @@ Example
 
 	    proj-get-local /mnt/usb-video/video-2019-04-01/trip.git
 EOF
-	exit 1
+    exit 1
 }
 
 # --------------------
 fCheckForGit()
 {
-	if git $cOrigin; then
-		echo 'Error: The current directory is a git dir.'
-		exit 1
-	fi
+    if git $cOrigin; then
+        echo 'Error: The current directory is a git dir.'
+        exit 1
+    fi
 }
 
 # --------------------
 fCheckPath()
 {
-	local pPath=$1
+    local pPath=$1
 
-	if [ ! -r $pPath ]; then
-		echo "Error: Could not find $pPath, or it is not readable"
-		exit 1
-	fi
+    if [ ! -r $pPath ]; then
+        echo "Error: Could not find $pPath, or it is not readable"
+        exit 1
+    fi
 }
 
 fGetLocal()
 {
-	local pPath=$1
+    local pPath=$1
 
-	git clone $pPath
-	echo "Done"
-	echo -n "Origin: "
-	git $cOrigin
+    git clone $pPath
+    echo "Done"
+    echo -n "Origin: "
+    git $cOrigin
 }
 
 # ====================
 # Main
 
 if [ $# -ne 1 ]; then
-	fUsage
+    fUsage
 fi
 
 gpPath=$1
diff --git a/git-proj-init b/git-proj-init
--- a/git-proj-init
+++ b/git-proj-init
@@ -3,9 +3,9 @@
 #--------------------
 fUsage()
 {
-	exit 1
-	
-	cat <<\EOF >/dev/null
+    exit 1
+
+    cat <<\EOF >/dev/null
 
 git proj init [-l [pDirPath]] [-e pDirPath] [-r [pDirPath]
 
@@ -39,34 +39,34 @@ Description
 Dependencies
 	packages: git, git-flow 
 EOF
-	exit 1
+    exit 1
 }
 
 # --------------------
 fCheckForPkg()
 {
-	local pPkg=$1
+    local pPkg=$1
 
-	if ! (dpkg -l $pPkg 2>/dev/null | grep -q "^ii *$pPkg"); then
-		echo "Error: Missing package: $pPkg"
-		exit 1
-	fi
+    if ! (dpkg -l $pPkg 2>/dev/null | grep -q "^ii *$pPkg"); then
+        echo "Error: Missing package: $pPkg"
+        exit 1
+    fi
 }
 
 # --------------------
 fCheckForGit()
 {
-	if git $cOrigin; then
-		echo "Error: .git already exists for the directory."
-		git branch
-		exit 1
-	fi
+    if git $cOrigin; then
+        echo "Error: .git already exists for the directory."
+        git branch
+        exit 1
+    fi
 }
 
 # --------------------
 fCreateGitDir()
 {
-	cat <<EOF >.gitignore
+    cat <<EOF >.gitignore
 *.tmp
 *~
 .cache/
@@ -78,20 +78,20 @@ proxy/
 thumbs/
 tmp/
 EOF
-	set -x
-	git init
-	git flow init
-	git checkout develop
-	git add .gitignore
-	git status
-	set +x
+    set -x
+    git init
+    git flow init
+    git checkout develop
+    git add .gitignore
+    git status
+    set +x
 }
 
 # ====================
 # Main
 
 if [ $# -eq 0 ]; then
-	fUsage
+    fUsage
 fi
 
 export cOrigin='config --get remote.origin.url'
@@ -109,7 +109,7 @@ exit 0
 #--------------------
 fUsage()
 {
-	cat <<EOF
+    cat <<EOF
 Usage:
 	proj-new-remote pPath
 	
@@ -128,84 +128,84 @@ Example
 
 	proj-new-remote /mnt/usb-video/video-2019-04-01
 EOF
-	exit 1
+    exit 1
 }
 
 # --------------------
 fCheckForGit()
 {
-	if [ ! -d .git ]; then
-		cat <<EOF
+    if [ ! -d .git ]; then
+        cat <<EOF
 Error: .git not found in current directory. cd to directory with .git
 in it, or use proj-new-local to create a new local repo.
 EOF
-		exit 1
-	fi
+        exit 1
+    fi
 }
 
 # --------------------
 fCheckPath()
 {
-	local pPath=$1
+    local pPath=$1
 
-	local tName=${PWD##*/}
+    local tName=${PWD##*/}
 
-	if [ ! -d $pPath ]; then
-		echo "Error: Could not find: $pPath"
-		exit 1
-	fi
-	if [ ! -w $pPath ]; then
-		echo "Error: $pPath is not writable for you."
-		exit 1
-	fi
-	if [ -e $pPath/$tName.git ]; then
-		echo "Error: $pPath/$tName.git already exists."
-		exit 1
-	fi
+    if [ ! -d $pPath ]; then
+        echo "Error: Could not find: $pPath"
+        exit 1
+    fi
+    if [ ! -w $pPath ]; then
+        echo "Error: $pPath is not writable for you."
+        exit 1
+    fi
+    if [ -e $pPath/$tName.git ]; then
+        echo "Error: $pPath/$tName.git already exists."
+        exit 1
+    fi
 }
 
 fCheckSpace()
 {
-	local pPath=$1
+    local pPath=$1
 
-	local tAvail
-	local tGitSize
+    local tAvail
+    local tGitSize
 
-	tAvail=$(df -BM $pPath --output=avail | tail -n1)
-	tAvail=${tAvail%M}
+    tAvail=$(df -BM $pPath --output=avail | tail -n1)
+    tAvail=${tAvail%M}
 
-	tGitSize=$(du -sm .git | awk '{print $1}')
-	let tGitSize*=2
+    tGitSize=$(du -sm .git | awk '{print $1}')
+    let tGitSize*=2
 
-	if [ $tGitSize -gt $tAvail ]; then
-		echo "Error: There is not enough space at $pPath"
-		echo "$pPath has ${tAvail}MB"
-		echo ".git needs ${tGitSize}MB"
-		exit 1
-	fi
+    if [ $tGitSize -gt $tAvail ]; then
+        echo "Error: There is not enough space at $pPath"
+        echo "$pPath has ${tAvail}MB"
+        echo ".git needs ${tGitSize}MB"
+        exit 1
+    fi
 }
 
 # --------------------
 fCreateRemote()
 {
-	local pPath=$1
+    local pPath=$1
 
-	local tSrcPath=$PWD
-	local tProjName=${PWD##*/}
+    local tSrcPath=$PWD
+    local tProjName=${PWD##*/}
 
-	set -x
-	cd $pPath &>/dev/null
-	git clone --bare --local --no-hardlinks --progress -v $tSrcPath/.git
-	cd - &>/dev/null
-	git remote add origin $pPath/$tProjName.git
-	set +x
+    set -x
+    cd $pPath &>/dev/null
+    git clone --bare --local --no-hardlinks --progress -v $tSrcPath/.git
+    cd - &>/dev/null
+    git remote add origin $pPath/$tProjName.git
+    set +x
 }
 
 fReport()
 {
-	echo 'Remote origin is now set to:'
-	git $cOrigin
-	cat <<EOF
+    echo 'Remote origin is now set to:'
+    git $cOrigin
+    cat <<EOF
 Be sure the disk is mounted and $gpPath exists.
 Then you can use: "git push origin develop"
 If the mount path is changed, use proj-remote-location update origin.
@@ -216,7 +216,7 @@ EOF
 # Main
 
 if [ $# -ne 1 ]; then
-	fUsage
+    fUsage
 fi
 
 gpPath=$1
diff --git a/git-proj-set b/git-proj-set
--- a/git-proj-set
+++ b/git-proj-set
@@ -3,8 +3,8 @@
 #--------------------
 fUsage()
 {
-	exit 1
-	cat <<\EOF >/dev/null
+    exit 1
+    cat <<\EOF >/dev/null
 git proj set [-l pExternalPath] [-e pRawPath]
 
     Define or redefine the gitproj options.
@@ -45,38 +45,38 @@ Example
 	will set the origin to: /mnt/usb-drive/video-2019-04-01/trip.git
 	if trip.git is found at the specified path.
 EOF
-	exit 1
+    exit 1
 }
 
 # --------------------
 fCheckForGit()
 {
-	if [ ! -d .git ]; then
-		echo 'Error: .git not found in current directory.'
-		exit 1
-	fi
+    if [ ! -d .git ]; then
+        echo 'Error: .git not found in current directory.'
+        exit 1
+    fi
 }
 
 fFindRemote()
 {
-	local pPath=$1
+    local pPath=$1
 
-	local tOrigin=$(git $cOrigin)
-	local tRemoteGit=${tOrigin##*/}
-	local tNewPath=$pPath/$tRemoteGit
+    local tOrigin=$(git $cOrigin)
+    local tRemoteGit=${tOrigin##*/}
+    local tNewPath=$pPath/$tRemoteGit
 
-	if [ ! -d $tNewPath ]; then
-		echo "Error: Could not find: $tNewPath"
-		exit 1
-	fi
-	echo $tNewPath
+    if [ ! -d $tNewPath ]; then
+        echo "Error: Could not find: $tNewPath"
+        exit 1
+    fi
+    echo $tNewPath
 }
 
 # ====================
 # Main
 
 if [ $# -ne 1 ]; then
-	fUsage
+    fUsage
 fi
 
 gpPath=$1
