Fixed up the package Makefile

diff --git a/package/Makefile b/package/Makefile
--- a/package/Makefile
+++ b/package/Makefile
@@ -35,22 +35,23 @@
 # make clean-release
 
 # --------------------
-include ver.mak
-
-# --------------------
 # Config
 
 SHELL = /bin/bash
 
 mRsyncOpt = -azP
 
+# --------------------
+include ver.mak
+
 # ----------------------------------------
 # Main targets
 
 # --------------------
-first : ver.mak ver.epm /usr/lib/git-core
-	touch ver.sh
-	make ver.mak
+first ver.mak : /usr/lib/git-core
+	@echo '--------------------'
+	@echo make first
+	mkver.pl -e 'mak'
 	@command -v git
 	@command -v epm
 	@command -v mkver.pl
@@ -64,17 +65,24 @@ first : ver.mak ver.epm /usr/lib/git-core
 	@command -v pod2markdown
 
 # --------------------
-build epm.list : clean ver.mak ver.epm ver.env
+# Build pseudo root of all files at dist/
+
+build epm.list : ver.mak ver.epm ver.env
+	@echo '--------------------'
+	@echo make build
 	if [ "$(USER)" = "root" ]; then exit 1; fi
 	cd ..; make gen-doc
+	-rm -rf dist
 	mkdir -p dist/usr/lib/git-core
 	mkdir -p dist/usr/share/doc/git-proj
 	mkdir -p dist/usr/share/man/man1
 	echo $(ProdVer) >../doc/VERSION
 	cp ../git-core/* dist/usr/lib/git-core
 	'rsync' -a ../doc/* dist/usr/share/doc/git-proj
-	-rm dist/usr/share/doc/git-proj/config/*.sav
-	-rm dist/usr/share/doc/git-proj/config/*.bak
+	-find dist -type f -name '*~' -exec rm {} \;
+	-find dist -type f -name '*.tmp' -exec rm {} \;
+	-find dist -type f -name '*.sav' -exec rm {} \;
+	-find dist -type f -name '*.bak*' -exec rm {} \;
 	cp ../LICENSE dist/usr/share/doc/git-proj
 	mkdir -p dist/usr/share/doc/git-proj/contrib
 	cp -p ../test/rm-trailing-sp ../test/bash-fmt ../test/bash-lint \
@@ -87,7 +95,11 @@ build epm.list : clean ver.mak ver.epm ver.env
 	mkepmlist -u root -g root --prefix / dist | patch-epm-list -f ./epm.patch >epm.list
 
 # --------------------
+# Non-package install - only for testing
+
 install :
+	@echo '--------------------'
+	@echo make install
 	if [ ! -f epm.list ]; then exit 1; fi
 	if [ "$(USER)" != "root" ]; then exit 1; fi
 	chown -R root:root dist/*
@@ -99,6 +111,8 @@ install :
 	# Only use this for testing.
 
 uninstall :
+	@echo '--------------------'
+	@echo make uninstall
 	if [ "$(USER)" != "root" ]; then exit 1; fi
 	rm /usr/lib/git-core/git-proj
 	rm /usr/lib/git-core/git-proj-*
@@ -106,59 +120,96 @@ uninstall :
 	rm -rf /usr/share/doc/git-proj
 
 # --------------------
+# Partial clean before a new build
+
 clean :
+	@echo '--------------------'
+	@echo make clean
 	-rm epm.list ver.cs ver.env ver.epm ver.h ver.java ver.pl ver.xml >/dev/null 2>&1
 	-rm -rf dist tmp >/dev/null 2>&1
 	-find .. -name '*~' -exec rm {} \; >/dev/null 2>&1
-	-find ../doc ../git-core -type f -name '*.tmp' -exec rm {} \; >/dev/null 2>&1
-	-find ../doc ../git-core -type f -name '*.sav' -exec rm {} \; >/dev/null 2>&1
-	-find ../doc ../git-core -type f -name '*.bak*' -exec rm {} \; >/dev/null 2>&1
+	-find ../doc ../git-core -type f -name '*.tmp' -exec rm {} \;
+	-find ../doc ../git-core -type f -name '*.sav' -exec rm {} \;
+	-find ../doc ../git-core -type f -name '*.bak*' -exec rm {} \;
 
+# Clean up all generated files (that are not versioned)
 dist-clean : clean
+	@echo '--------------------'
+	@echo make dist-clean
 	-cd ../test; make dist-clean
 	-rm -rf pkg >/dev/null 2>&1
 
-archive :
+archive : dist-clean
+	@echo '--------------------'
+	@echo make archive
 	cd ../..; tar -czf gitproj-$$(cat gitproj/doc/VERSION).tgz --exclude=.git --exclude-vcs gitproj test-env*.tgz
 
 # --------------------
+# This section is for automated build/release
+
 test-package : epm.list $(ProdOSDist).require
+	@echo '--------------------'
+	@echo make test-package
 	if [ "$(USER)" = "root" ]; then exit 1; fi
-	-rm -rf pkg ver.epm >/dev/null 2>&1
+	-rm -rf pkg ver.epm ver.env >/dev/null 2>&1
 	mkdir pkg
-	export RELEASE=0; mkver.pl -e epm
+	export RELEASE=0; mkver.pl -e 'epm env'
+	@echo '--------------------'
+	cat ver.epm
+	@echo '--------------------'
 	epm -v -f native -m $(ProdOSDist)-$(ProdArch) --output-dir pkg $(ProdName) ver.epm
 	epm -v -f portable -m $(ProdOSDist)-$(ProdArch) --output-dir pkg $(ProdName) ver.epm
 
-test-init :
-	-ssh $(ProdRelServer) mkdir -p $(ProdDevDir)
-	ssh $(ProdRelServer) test -d $(ProdDevDir)
+test-init : ver.env
+	@echo '--------------------'
+	@echo make test-init
+	-. ./ver.env; ssh $(ProdRelServer) mkdir -p $(ProdDevDir)
+	. ./ver.env; ssh $(ProdRelServer) test -d $(ProdDevDir)
+	# Run this once before automated test-release
 
-test-release :
-	scp -i ~/.ssh/id.hamp pkg/$(ProdName)-*.deb hamp@$(ProdRelServer):/$(ProdRelCategory)
+test-release : ver.env
+	@echo '--------------------'
+	@echo make test-release
+	@echo '--------------------'
+	cat ver.env
+	@echo '--------------------'
+	. ./ver.env; scp -i ~/.ssh/id.hamp pkg/$(ProdName)-*.deb hamp@$(ProdRelServer):/$(ProdRelCategory)
+	. ./ver.env; scp -i ~/.ssh/id.hamp pkg/$(ProdName)-*.tar.gz hamp@$(ProdRelServer):/$(ProdRelCategory)
 
 # --------------------
+# Use this to make release candidates or final builds
+
 package : epm.list $(ProdOSDist).require
+	@echo '--------------------'
+	@echo make package
 	if [ "$(USER)" = "root" ]; then exit 1; fi
-	-rm -rf pkg ver.epm >/dev/null 2>&1
+	-rm -rf pkg ver.epm ver.env >/dev/null 2>&1
 	mkdir pkg
-	export RELEASE=1; mkver.pl -e epm
+	export RELEASE=1; mkver.pl -e 'epm env'
+	##. ./ver.env; echo "%release rc$$ProdBuild.$$ProdBuildTime" >>ver.epm
+	@echo '--------------------'
+	cat ver.epm
+	@echo '--------------------'
 	epm -v -f native -m $(ProdOSDist)-$(ProdArch) --output-dir pkg $(ProdName) ver.epm
 	epm -v -f portable -m $(ProdOSDist)-$(ProdArch) --output-dir pkg $(ProdName) ver.epm
 	# Set ProdRC for Release Candidate packages
 	# Has CHANGES.md been updated?
 	# If stable release, merge develop to main branch
 
-release : ver.mak
-	-ssh $(ProdRelServer) mkdir -p $(ProdRelDir)
-	ssh $(ProdRelServer) test -d $(ProdRelDir)
-	'rsync' $(mRsyncOpt) pkg/$(ProdName)-* $(ProdRelServer):$(ProdRelDir)
-
-clean-rc-release : TBD
-	# Remove all $(ProdName) Release Candidates from repo
+release : ver.env
+	@echo '--------------------'
+	@echo make release
+	@echo '--------------------'
+	cat ver.env
+	@echo '--------------------'
+	-. ./ver.env; ssh $(ProdRelServer) mkdir -p $(ProdRelDir)
+	. ./ver.env; ssh $(ProdRelServer) test -d $(ProdRelDir)
+	. ./ver.env; 'rsync' $(mRsyncOpt) pkg/$(ProdName)-* $(ProdRelServer):$(ProdRelDir)
 
 # --------------------
 tag : ver.mak
+	@echo '--------------------'
+	@echo make tag
 	-git commit -am Updated
 	git tag -f -a -m "Released to: $(ProdRelServer):$(ProdRelDir)" $(ProdTag)
 	echo "# --------------------" >>REL-VERSION
@@ -174,6 +225,10 @@ tag : ver.mak
 # --------------------
 # Work Targets
 
-ver.epm ver.env ver.mak : ver.sh
+ver.epm ver.env : ver.sh
 	if [ "$(USER)" = "root" ]; then exit 1; fi
-	mkver.pl -e 'env epm mak'
+	mkver.pl -e 'env epm'
+
+# ver.mak : ver.sh
+#	if [ "$(USER)" = "root" ]; then exit 1; fi
+#	mkver.pl -e 'mak'
